name: Deploy to Firebase Hosting on Push

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Descarga el código del repositorio
      - uses: actions/checkout@v4

      # Configura caché para dependencias de Node.js
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Instalación de dependencias
      - name: Install dependencies
        run: npm ci --retry=3 --timeout=60000

      # Construcción del proyecto
      - name: Build project
        run: npm run build

      # Despliegue a Firebase Hosting (producción)
      - name: Deploy to Firebase Hosting
        run: npx firebase-tools deploy --only hosting --project adstaller3frontend
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
