name: Deploy to Firebase Hosting on Push

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Descarga el código del repositorio
      - uses: actions/checkout@v4

      # Configuración de caché para Node.js
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Instalación de dependencias con timeout y reintentos
      - name: Install dependencies
        run: npm ci --retry=3 --timeout=60000

      # Construcción del proyecto React
      - name: Build project
        run: npm run build

      # Despliegue directo a Firebase Hosting (producción)
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ADSTALLER3FRONTEND }}
          projectId: adstaller3frontend
